export default [
  'units-in-system',
	'js-best-practices-config-ci-part-d',
  'js-best-practices-config-unit-tests-part-c',
  'js-best-practices-config-linter-part-b',
  'js-best-practices-config-ts-part-a',
  'private-vpn-on-aws',
  'photoprism-on-rsp',
  'google-photos-alternative',
  'mulit-platform-cpp',
  'flashing-tasmota-on-sonoff-rf-bridge',
  'environments-variables-and-frontend',
  'flashing-tasmota-on-tuya-ir-bridge',
  'earth-coordinates-and-spatial-data',
  'dummy-recursion-in-js-and-its-solution-with-async-await',
]